
-- Seed all default global settings from useGlobalSettings.ts defaults
-- Category: fiscal_rules (IR 2025)
INSERT INTO public.global_settings (category, key, value, label, description, value_type, year, is_active, display_order) VALUES
('fiscal_rules', 'tax_brackets', '[{"seuil":0,"taux":0},{"seuil":11294,"taux":11},{"seuil":28797,"taux":30},{"seuil":82341,"taux":41},{"seuil":177106,"taux":45}]', 'Tranches d''imposition IR', 'Barème progressif de l''impôt sur le revenu 2025', 'array', 2025, true, 1),
('fiscal_rules', 'social_charges_rate', '17.2', 'Prélèvements sociaux', 'Taux global des prélèvements sociaux sur revenus du capital', 'percentage', 2025, true, 2),
('fiscal_rules', 'pfu_rate', '12.8', 'PFU (Flat Tax) - Part IR', 'Taux forfaitaire d''impôt sur le revenu dans le PFU', 'percentage', 2025, true, 3),
('fiscal_rules', 'csg_deductible_rate', '6.8', 'CSG déductible', 'Part de CSG déductible du revenu imposable', 'percentage', 2025, true, 4),
('fiscal_rules', 'per_ceiling_rate', '10', 'Plafond PER - Taux', 'Pourcentage du revenu net pour le plafond PER', 'percentage', 2025, true, 5),
('fiscal_rules', 'per_ceiling_min', '4399', 'Plafond PER - Minimum', 'Plancher de déduction PER', 'currency', 2025, true, 6),
('fiscal_rules', 'per_ceiling_max', '35194', 'Plafond PER - Maximum', 'Plafond maximum de déduction PER', 'currency', 2025, true, 7),
('fiscal_rules', 'dons_75_rate', '75', 'Dons - Taux 75%', 'Taux de réduction pour dons aux organismes d''aide (Coluche)', 'percentage', 2025, true, 8),
('fiscal_rules', 'dons_75_ceiling', '1000', 'Dons - Plafond 75%', 'Plafond des dons éligibles au taux de 75%', 'currency', 2025, true, 9),
('fiscal_rules', 'dons_66_rate', '66', 'Dons - Taux 66%', 'Taux de réduction pour dons aux associations d''intérêt général', 'percentage', 2025, true, 10),
('fiscal_rules', 'dons_income_limit_rate', '20', 'Dons - Limite revenu', 'Limite des dons en % du revenu imposable', 'percentage', 2025, true, 11),
('fiscal_rules', 'aide_domicile_rate', '50', 'Aide à domicile - Taux', 'Taux du crédit d''impôt emploi à domicile', 'percentage', 2025, true, 12),
('fiscal_rules', 'aide_domicile_ceiling', '12000', 'Aide à domicile - Plafond', 'Plafond des dépenses d''emploi à domicile', 'currency', 2025, true, 13),
('fiscal_rules', 'garde_enfant_rate', '50', 'Garde enfant - Taux', 'Taux du crédit d''impôt frais de garde', 'percentage', 2025, true, 14),
('fiscal_rules', 'garde_enfant_ceiling', '3500', 'Garde enfant - Plafond', 'Plafond par enfant pour le crédit d''impôt garde', 'currency', 2025, true, 15),
('fiscal_rules', 'pme_reduction_rate', '18', 'PME - Taux réduction', 'Taux de réduction IR pour investissement PME', 'percentage', 2025, true, 16),
('fiscal_rules', 'pme_ceiling_single', '50000', 'PME - Plafond célibataire', 'Plafond d''investissement PME pour personne seule', 'currency', 2025, true, 17),
('fiscal_rules', 'pme_ceiling_couple', '100000', 'PME - Plafond couple', 'Plafond d''investissement PME pour couple', 'currency', 2025, true, 18),
('fiscal_rules', 'esus_reduction_rate', '18', 'ESUS - Taux réduction', 'Taux de réduction IR pour investissement ESUS', 'percentage', 2025, true, 19),
('fiscal_rules', 'esus_ceiling', '13000', 'ESUS - Plafond', 'Plafond spécifique niche fiscale ESUS', 'currency', 2025, true, 20),
('fiscal_rules', 'niche_ceiling_base', '10000', 'Niche fiscale - Plafond base', 'Plafond global des niches fiscales', 'currency', 2025, true, 21),
('fiscal_rules', 'niche_ceiling_esus', '13000', 'Niche fiscale - Plafond ESUS', 'Plafond niches fiscales incluant ESUS', 'currency', 2025, true, 22),
('fiscal_rules', 'niche_ceiling_outremer', '18000', 'Niche fiscale - Plafond Outre-mer', 'Plafond niches fiscales incluant Outre-mer', 'currency', 2025, true, 23),
('fiscal_rules', 'girardin_ceiling_part', '44', 'Girardin - Plafond par part', 'Plafond Girardin par part fiscale (k€)', 'currency', 2025, true, 24),
('fiscal_rules', 'girardin_rate_t1', '125', 'Girardin - Taux T1', 'Taux de rendement Girardin tranche 1', 'percentage', 2025, true, 25),
('fiscal_rules', 'girardin_rate_t2', '120', 'Girardin - Taux T2', 'Taux de rendement Girardin tranche 2', 'percentage', 2025, true, 26),
('fiscal_rules', 'girardin_rate_t3', '117', 'Girardin - Taux T3', 'Taux de rendement Girardin tranche 3', 'percentage', 2025, true, 27),
('fiscal_rules', 'girardin_rate_t4', '112', 'Girardin - Taux T4', 'Taux de rendement Girardin tranche 4', 'percentage', 2025, true, 28),
('fiscal_rules', 'micro_bic_abatement', '50', 'Micro-BIC - Abattement', 'Taux d''abattement forfaitaire Micro-BIC', 'percentage', 2025, true, 29),
('fiscal_rules', 'micro_bic_threshold', '77700', 'Micro-BIC - Seuil', 'Seuil de chiffre d''affaires Micro-BIC', 'currency', 2025, true, 30),
('fiscal_rules', 'pinel_rate_6_years', '9', 'Pinel - Taux 6 ans', 'Taux Pinel métropole sur 6 ans', 'percentage', 2025, true, 31),
('fiscal_rules', 'pinel_rate_9_years', '12', 'Pinel - Taux 9 ans', 'Taux Pinel métropole sur 9 ans', 'percentage', 2025, true, 32),
('fiscal_rules', 'pinel_rate_12_years', '14', 'Pinel - Taux 12 ans', 'Taux Pinel métropole sur 12 ans', 'percentage', 2025, true, 33),
('fiscal_rules', 'pinel_om_rate_6_years', '23', 'Pinel OM - Taux 6 ans', 'Taux Pinel Outre-mer sur 6 ans', 'percentage', 2025, true, 34),
('fiscal_rules', 'pinel_om_rate_9_years', '29', 'Pinel OM - Taux 9 ans', 'Taux Pinel Outre-mer sur 9 ans', 'percentage', 2025, true, 35),
('fiscal_rules', 'pinel_om_rate_12_years', '32', 'Pinel OM - Taux 12 ans', 'Taux Pinel Outre-mer sur 12 ans', 'percentage', 2025, true, 36),
('fiscal_rules', 'pinel_ceiling', '300000', 'Pinel - Plafond investissement', 'Plafond d''investissement Pinel', 'currency', 2025, true, 37),

-- Category: simulation_defaults
('simulation_defaults', 'default_tmi', '30', 'TMI par défaut', 'Tranche marginale d''imposition par défaut', 'percentage', null, true, 1),
('simulation_defaults', 'default_interest_rate', '3.2', 'Taux d''intérêt par défaut', 'Taux d''intérêt immobilier par défaut', 'percentage', null, true, 2),
('simulation_defaults', 'default_insurance_rate', '0.34', 'Taux assurance par défaut', 'Taux d''assurance emprunteur par défaut', 'percentage', null, true, 3),
('simulation_defaults', 'default_loan_duration', '20', 'Durée emprunt par défaut', 'Durée d''emprunt par défaut en années', 'number', null, true, 4),
('simulation_defaults', 'default_amort_duration_immo', '25', 'Durée amortissement immo', 'Durée d''amortissement immobilier LMNP', 'number', null, true, 5),
('simulation_defaults', 'default_amort_duration_mobilier', '7', 'Durée amortissement mobilier', 'Durée d''amortissement mobilier LMNP', 'number', null, true, 6),
('simulation_defaults', 'max_debt_ratio', '35', 'Taux d''endettement max', 'Taux d''endettement maximum recommandé', 'percentage', null, true, 7),
('simulation_defaults', 'min_living_remainder_adult', '400', 'Reste à vivre min adulte', 'Reste à vivre minimum par adulte', 'currency', null, true, 8),
('simulation_defaults', 'min_living_remainder_child', '300', 'Reste à vivre min enfant', 'Reste à vivre minimum par enfant', 'currency', null, true, 9),
('simulation_defaults', 'epargne_niveau_minimum_mois', '2', 'Épargne - Niveau minimum', 'Nombre de mois pour le niveau minimum', 'number', null, true, 10),
('simulation_defaults', 'epargne_niveau_confortable_mois', '4', 'Épargne - Niveau confortable', 'Nombre de mois pour le niveau confortable', 'number', null, true, 11),
('simulation_defaults', 'epargne_niveau_optimal_mois', '6', 'Épargne - Niveau optimal', 'Nombre de mois pour le niveau optimal', 'number', null, true, 12),
('simulation_defaults', 'epargne_coef_cdi_tech', '1.0', 'Coef CDI tech', 'Coefficient métier CDI tech', 'number', null, true, 13),
('simulation_defaults', 'epargne_coef_cdi_non_tech', '1.2', 'Coef CDI non tech', 'Coefficient métier CDI non tech', 'number', null, true, 14),
('simulation_defaults', 'epargne_coef_independant', '1.5', 'Coef indépendant', 'Coefficient métier indépendant', 'number', null, true, 15),
('simulation_defaults', 'epargne_coef_variable', '1.5', 'Coef revenu variable', 'Coefficient métier revenu variable', 'number', null, true, 16),
('simulation_defaults', 'epargne_seuil_charges_bon', '0.3', 'Seuil charges bon', 'Seuil ratio charges/revenus bon', 'number', null, true, 17),
('simulation_defaults', 'epargne_seuil_charges_moyen', '0.5', 'Seuil charges moyen', 'Seuil ratio charges/revenus moyen', 'number', null, true, 18),
('simulation_defaults', 'epargne_seuil_charges_eleve', '0.6', 'Seuil charges élevé', 'Seuil ratio charges/revenus élevé', 'number', null, true, 19),
('simulation_defaults', 'epargne_objectif_mois', '12', 'Objectif épargne mois', 'Nombre de mois objectif pour épargne de précaution', 'number', null, true, 20),

-- Category: product_constants
('product_constants', 'espp_discount_rate', '15', 'ESPP - Taux décote', 'Taux de décote ESPP par défaut', 'percentage', null, true, 1),
('product_constants', 'expected_market_growth', '8', 'Croissance marché attendue', 'Taux de croissance marché attendu', 'percentage', null, true, 2),
('product_constants', 'rsu_social_charges_employer', '50', 'RSU - Charges patronales', 'Taux charges patronales sur RSU', 'percentage', null, true, 3),
('product_constants', 'retirement_age_default', '64', 'Âge retraite par défaut', 'Âge légal de départ à la retraite', 'number', null, true, 4),
('product_constants', 'return_rate_short', '3', 'Rendement court terme', 'Taux de rendement attendu court terme', 'percentage', null, true, 5),
('product_constants', 'return_rate_medium', '6', 'Rendement moyen terme', 'Taux de rendement attendu moyen terme', 'percentage', null, true, 6),
('product_constants', 'return_rate_long', '8', 'Rendement long terme', 'Taux de rendement attendu long terme', 'percentage', null, true, 7),
('product_constants', 'return_rate_very_long', '10', 'Rendement très long terme', 'Taux de rendement attendu très long terme', 'percentage', null, true, 8),

-- Category: lead_qualification
('lead_qualification', 'rang_1_min_income', '0', 'Rang 1 - Revenu min', 'Revenu minimum pour rang 1', 'currency', null, true, 1),
('lead_qualification', 'rang_1_max_income', '40000', 'Rang 1 - Revenu max', 'Revenu maximum pour rang 1', 'currency', null, true, 2),
('lead_qualification', 'rang_2_min_income', '40001', 'Rang 2 - Revenu min', 'Revenu minimum pour rang 2', 'currency', null, true, 3),
('lead_qualification', 'rang_2_max_income', '80000', 'Rang 2 - Revenu max', 'Revenu maximum pour rang 2', 'currency', null, true, 4),
('lead_qualification', 'rang_3_min_income', '80001', 'Rang 3 - Revenu min', 'Revenu minimum pour rang 3', 'currency', null, true, 5),
('lead_qualification', 'rang_3_max_income', '999999999', 'Rang 3 - Revenu max', 'Revenu maximum pour rang 3', 'currency', null, true, 6),

-- Category: recommendation_thresholds
('recommendation_thresholds', 'cta_tmi_high_threshold', '30', 'Seuil TMI élevé', 'TMI à partir duquel proposer optimisation fiscale', 'percentage', null, true, 1),
('recommendation_thresholds', 'cta_tmi_very_high_threshold', '41', 'Seuil TMI très élevé', 'TMI à partir duquel proposer PER/Girardin', 'percentage', null, true, 2),
('recommendation_thresholds', 'cta_per_eligible_min_tmi', '30', 'PER - TMI min éligible', 'TMI minimum pour recommander le PER', 'percentage', null, true, 3),
('recommendation_thresholds', 'cta_per_optimal_min_tmi', '41', 'PER - TMI optimal', 'TMI à partir duquel le PER est optimal', 'percentage', null, true, 4),
('recommendation_thresholds', 'cta_epargne_insuffisante_mois', '2', 'Épargne insuffisante', 'Seuil mois en dessous = épargne insuffisante', 'number', null, true, 5),
('recommendation_thresholds', 'cta_epargne_ok_mois', '4', 'Épargne OK', 'Seuil mois pour épargne correcte', 'number', null, true, 6),
('recommendation_thresholds', 'cta_epargne_excedent_mois', '6', 'Épargne excédentaire', 'Seuil mois au-dessus = investir excédent', 'number', null, true, 7),
('recommendation_thresholds', 'cta_capacite_emprunt_bon', '25', 'Endettement bon', 'Taux d''endettement considéré comme bon', 'percentage', null, true, 8),
('recommendation_thresholds', 'cta_capacite_emprunt_attention', '33', 'Endettement attention', 'Taux d''endettement nécessitant attention', 'percentage', null, true, 9),
('recommendation_thresholds', 'cta_capacite_emprunt_danger', '40', 'Endettement danger', 'Taux d''endettement dangereux', 'percentage', null, true, 10),
('recommendation_thresholds', 'cta_reste_a_vivre_min_adulte', '400', 'Reste à vivre min adulte', 'Reste à vivre minimum par adulte pour CTA', 'currency', null, true, 11),
('recommendation_thresholds', 'cta_reste_a_vivre_min_enfant', '300', 'Reste à vivre min enfant', 'Reste à vivre minimum par enfant pour CTA', 'currency', null, true, 12),
('recommendation_thresholds', 'cta_lmnp_min_recettes', '15000', 'LMNP - Recettes min', 'Recettes minimum pour recommander LMNP réel', 'currency', null, true, 13),
('recommendation_thresholds', 'cta_lmnp_charges_threshold', '0.5', 'LMNP - Seuil charges', 'Ratio charges/recettes LMNP pour basculer au réel', 'number', null, true, 14),
('recommendation_thresholds', 'cta_espp_gain_min_percent', '15', 'ESPP - Gain min', 'Gain minimum ESPP pour recommander participation', 'percentage', null, true, 15),
('recommendation_thresholds', 'cta_espp_vente_immediat_threshold', '50', 'ESPP - Seuil vente immédiate', 'Seuil pour recommander vente immédiate ESPP', 'percentage', null, true, 16),
('recommendation_thresholds', 'cta_girardin_min_ir', '5000', 'Girardin - IR min', 'IR minimum pour recommander Girardin', 'currency', null, true, 17),
('recommendation_thresholds', 'cta_pme_min_ir', '3000', 'PME - IR min', 'IR minimum pour recommander investissement PME', 'currency', null, true, 18),
('recommendation_thresholds', 'lead_patrimoine_min_premium', '100000', 'Lead - Patrimoine premium', 'Patrimoine minimum pour lead premium', 'currency', null, true, 19),
('recommendation_thresholds', 'lead_revenu_min_priority', '80000', 'Lead - Revenu prioritaire', 'Revenu minimum pour lead prioritaire', 'currency', null, true, 20)

ON CONFLICT DO NOTHING;
